name: Build and push Docker image
on:
  push:
    branches: [main]
jobs:
  dotnet:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.repository == 'xSke/PluralKit'
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/378
          context: .
          push: true
          tags: |
            ghcr.io/pluralkit/pluralkit:${{ github.sha }}
            ghcr.io/pluralkit/pluralkit:latest
          cache-from: type=registry,ref=ghcr.io/pluralkit/pluralkit
          cache-to: type=inline

  gateway:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.repository == 'xSke/PluralKit'
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/378
          context: .
          push: true
          file: Dockerfile.gateway # or whatever
          tags: |
            ghcr.io/pluralkit/gateway:${{ github.sha }}
            ghcr.io/pluralkit/gateway:latest
          cache-from: type=registry,ref=ghcr.io/pluralkit/gateway
          cache-to: type=inline
