name: .net checks

on:
  push:
    paths:
      - .github/workflows/dotnet.yml
      - "Myriad/**"
      - "PluralKit.API/**"
      - "PluralKit.Bot/**"
      - "PluralKit.Core/**"
  pull_request:
    paths:
      - .github/workflows/dotnet.yml
      - "Myriad/**"
      - "PluralKit.API/**"
      - "PluralKit.Bot/**"
      - "PluralKit.Core/**"

jobs:
  test:
    name: "run .net tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: install uniffi
        run: cargo install uniffi-bindgen-cs --git https://github.com/90-008/uniffi-bindgen-cs

      - name: generate command parser bindings
        run: |
          cargo -Z unstable-options build --package commands --lib --release --artifact-dir obj/
          uniffi-bindgen-cs "obj/libcommands.so" --library --out-dir="./PluralKit.Bot"
          cargo run --package commands --bin write_cs_glue -- "./PluralKit.Bot"/commandtypes.cs

      - name: Run automated tests
        run: dotnet test --configuration Release

  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Run dotnet-format
        run: dotnet format --no-restore --verify-no-changes
