name: Build scheduled tasks runner Docker image

on:
  push:
    branches: [main]
    paths:
      - 'scheduled_tasks/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.repository == 'PluralKit/PluralKit'
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/378
          context: .
          file: scheduled_tasks/Dockerfile
          push: true
          tags: |
            ghcr.io/pluralkit/scheduled_tasks:${{ env.BRANCH_NAME }}
            ghcr.io/pluralkit/scheduled_tasks:${{ github.sha }}
            ghcr.io/pluralkit/scheduled_tasks:latest
          cache-from: type=registry,ref=ghcr.io/pluralkit/scheduledtasks:${{ env.BRANCH_NAME }}
          cache-to: type=inline
